services:
  postgres:
    image: postgres:16
    container_name: reachinbox-email-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reachinbox-email

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: reachinbox-email-redis

    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: